name: World

on: 
  workflow_run:
    workflows: 'Spin'
    branches:
        - main
    types:
        - completed

jobs:
    world:
        runs-on:
            - ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Print Greeting
              run: |
                echo "Hello, World!"
                date
                pwd
                ls -la