name: Spin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  spin:
    runs-on: ubuntu-latest
    environment:
      name: casino
      url: https://github.com

    steps:
      - uses: actions/checkout@v4

      - name: Print Greeting
        run: |
          echo "Hello, Spin!"
          date
          pwd
          ls -la

  reel_1:
    needs: spin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Greeting
        run: |
          echo "Hello, Github Actions!"
          date
          pwd
          ls -la

  reel_2:
    needs: reel_1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Greeting
        run: |
          echo "Hello, World!"
          date
          pwd
          ls -la

  reel_3:
    needs: reel_2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Greeting
        run: |
          echo "Hello, World!"
          date
          pwd
          ls -la
  
  deploy:
    needs:
      - spin
      - reel_1
      - reel_2
      - reel_3
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4

      - name: Jackpot!
        run: |
          echo "You win!"

